### ISSUE TITLE
"Buggy man" lives on Codespace

### ISSUE THREAD

**Issue by M1st3rfr10** [cs50/codespace#109]
My experience using Codespace is very frustrating: the response is very slow, and when I recompile the program, it still shows the old version. My Internet connection is very bad but I already tried a faster one, and this problem continues; I've been stuck for two weeks without being able to learn or advance in the course; I forget to mention that I already updated Codespace and Chrome, and the cache is clean.
With Scratch everything runs smooth

**Comment by rongxin-liu** [comment]
Sorry for the frustration. I'm afraid we have no control over internet connection and we do not manage Codespaces directly. If you thing the issue was with CS50 Codespace specifically, please send the following information to sysadmins@cs50.harvard.edu:

1. Where are you located?
2. What is your ISP (internet service provider)? 
3. Send us the content of [cs50.dev/debug](http://cs50.dev/debug)

In addition, for any Codespaces issue, please also post them on https://github.com/orgs/community/discussions/categories/codespaces

**Comment by M1st3rfr10** [comment]
Hi, thank you for your fast response but the issue was fixed. Have a great day! :)
