### ISSUE TITLE
Could "Teacher" make the codespace repository public?

### ISSUE THREAD

**Issue by mkotsovoulou** [cs50/codespace#48]
I was just thinking, whether the GitHub repo (where the code in the codespace is located)
 could have the option to be made public?
As such students could copy/clone the code demonstrated in class by the instructor...
_Just an idea as a teaching modality_

**Comment by dmalan** [comment]
Ah, I like the idea, but I suspect we'll want to keep the full `code50` backups private, since almost everything from one's codespace is preserved there. And if a teacher were to use their same codespace for preparing solutions, viewing students' code, etc., they wouldn't necessarily want to make everything public. Will see if we can make it easier, though, to share specific folders and such somehow!

**Comment by mkotsovoulou** [comment]
I totally agree….
Currently I open a live share session so students can copy…

Thank you David for taking the time to reply!

Best, 
Maira K
